language: c

compiler:
  - clang
  - gcc

sudo: false

addons:
  apt:
    packages:
      - libid3-3.8.3-dev
      - libcurl4-gnutls-dev

script: gem install mustache -v=0.7.0 && gem install ronn && autoreconf -fvi && ./configure && make all && make check && make clean
