language: c

compiler:
  - clang
  - gcc

sudo: false

addons:
  apt:
    packages:
      - libid3-3.8.3-dev
      - libcurl4-gnutls-dev

script: gem install ronn && autoreconf -fvi && ./configure --disable-id3lib && make all && make check && make clean
